insert into subject(id, name) values (1, 'health')
insert into subject(id, name) values (2, 'technology')
insert into subject(id, name) values (3, 'climate')

insert into survey(id, subject_id, gender, age_range_left, age_range_right) values (1, 1, 0, 30, 70)
insert into survey(id, subject_id, gender, age_range_left, age_range_right) values (2, 1, 1, 30, 70)
insert into survey(id, subject_id, gender, age_range_left, age_range_right) values (3, 2, 0, 15, 50)
insert into survey(id, subject_id, gender, age_range_left, age_range_right) values (4, 2, 1, 15, 50)
insert into survey(id, subject_id, gender, age_range_left, age_range_right) values (5, 3, 0, 15, 40)
insert into survey(id, subject_id, gender, age_range_left, age_range_right) values (6, 3, 1, 15, 40)